In [38]:
# Paso 1: Importamos librerias 
import pandas
import numpy

#### Paso 1: Cargamos el DataFrame en memoria a partir de un archivo csv

In [53]:
# vamos a leer el contenido del archivo csv, para que funcione es importante que el archivo csv este en el mismo directorio que esta notebook
varDataFrame = pandas.read_csv('Detalle de Ventas 0124 - Detalle de Ventas.csv')
varDataFrame

,NEGOCIO,CAJA,SUCURSAL,Fecha de Venta,Comprobante,Número,Descripción Sucursal de registración,Tipo de producto,Descripción,Precio,Cantidad,Tot % bonif.,Total Facturado,Hora de Venta,Observaciones,Código reducido,Concatenado,Dia de la semana,Hora del dia
0,BIKE COMPANY,Caja RMA,BIKE COMPANY S159,1/1/2024,Caja 2,0,Sucursal VJPSA BB Bike Company,SIN DETALLE,SIN DETALLE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Caja 20,[1] Lunes,0
1,BIKE COMPANY,Caja RMA,BIKE COMPANY S159,2/1/2024,Caja 2,0,Sucursal VJPSA BB Bike Company,SIN DETALLE,SIN DETALLE,NaN,NaN,NaN,"33.900,00",NaN,NaN,NaN,Caja 20,[2] Martes,0
2,BIKE COMPANY,Caja RMA,BIKE COMPANY S159,3/1/2024,Caja 2,0,Sucursal VJPSA BB Bike Company,SIN DETALLE,SIN DETALLE,NaN,NaN,NaN,"301.400,00",NaN,NaN,NaN,Caja 20,[3] Miércoles,0
3,BIKE COMPANY,Caja RMA,BIKE COMPANY S159,4/1/2024,Caja 2,0,Sucursal VJPSA BB Bike Company,SIN DETALLE,SIN DETALLE,NaN,NaN,NaN,"6.900,00",NaN,NaN,NaN,Caja 20,[4] Jueves,0
4,BIKE COMPANY,Caja RMA,BIKE COMPANY S159,5/1/2024,Caja 2,0,Sucursal VJPSA BB Bike Company,SIN DETALLE,SIN DETALLE,NaN,NaN,NaN,"22.800,00",NaN,NaN,NaN,Caja 20,[5] Viernes,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1269,MHAZZ Store,Caja SoftL,PR SAN MARTIN 698,31/1/2024,TKB036,27906,Sucursal VJPSA CP San Martin 698,FILM,HYDROGEL HAXLY S/M (SIN MODELO) ORIGINAL,"5.900,00",1,0,"5.900,00",31/1/2024 9:33:37,NaN,NaN,TKB03627906,[3] Miércoles,9
1270,MHAZZ Store,Caja SoftL,PR SAN MARTIN 698,31/1/2024,TKB036,27907,Sucursal VJPSA CP San Martin 698,CABLE,USB SOUL LIGHTNING GENERICO BLANCO,"5.900,00",1,0,"5.900,00",31/1/2024 17:23:56,NaN,NaN,TKB03627907,[3] Miércoles,17
1271,MHAZZ Store,Caja SoftL,PR SAN MARTIN 698,31/1/2024,TKB036,27908,Sucursal VJPSA CP San Martin 698,FILM,HYDROGEL HAXLY S/M (SIN MODELO) ORIGINAL,"5.900,00",2,0,"11.800,00",31/1/2024 17:40:12,NaN,NaN,TKB03627908,[3] Miércoles,17
1272,MHAZZ Store,Caja SoftL,PR SAN MARTIN 698,31/1/2024,TKB036,27909,Sucursal VJPSA CP San Martin 698,CABLE,USB ALO MICROUSB ORIGINAL,"3.500,00",1,0,"3.500,00",31/1/2024 19:47:43,NaN,NaN,TKB03627909,[3] Miércoles,19
1273,MHAZZ Store,Caja SoftL,PR SAN MARTIN 698,31/1/2024,TKB036,27909,Sucursal VJPSA CP San Martin 698,AUR,INTRAULAR SOUL S150 GENERICO BLANCO,"3.500,00",1,0,"3.500,00",31/1/2024 19:47:43,NaN,NaN,TKB03627909,[3] Miércoles,19

### Transformaciones: Agregar una nueva columna

#### Opción 1: Agregar una nueva columna con un valor constante

In [54]:
# De esta forma agrego una nueva columna llamada "Vendedor" con el valor definido por el usuario 'Sin Vendedor'
varDataFrame['Vendedor'] = "Sin Vendedor"
varDataFrame[['SUCURSAL', 'Fecha de Venta', 'Precio', 'Cantidad', 'Tot % bonif.', 'Total Facturado', 'Vendedor' ]]

,SUCURSAL,Fecha de Venta,Precio,Cantidad,Tot % bonif.,Total Facturado,Vendedor
0,BIKE COMPANY S159,1/1/2024,NaN,NaN,NaN,NaN,Sin Vendedor
1,BIKE COMPANY S159,2/1/2024,NaN,NaN,NaN,"33.900,00",Sin Vendedor
2,BIKE COMPANY S159,3/1/2024,NaN,NaN,NaN,"301.400,00",Sin Vendedor
3,BIKE COMPANY S159,4/1/2024,NaN,NaN,NaN,"6.900,00",Sin Vendedor
4,BIKE COMPANY S159,5/1/2024,NaN,NaN,NaN,"22.800,00",Sin Vendedor
...,...,...,...,...,...,...,...
1269,PR SAN MARTIN 698,31/1/2024,"5.900,00",1,0,"5.900,00",Sin Vendedor
1270,PR SAN MARTIN 698,31/1/2024,"5.900,00",1,0,"5.900,00",Sin Vendedor
1271,PR SAN MARTIN 698,31/1/2024,"5.900,00",2,0,"11.800,00",Sin Vendedor
1272,PR SAN MARTIN 698,31/1/2024,"3.500,00",1,0,"3.500,00",Sin Vendedor
1273,PR SAN MARTIN 698,31/1/2024,"3.500,00",1,0,"3.500,00",Sin Vendedor

#### Opción 2: Agregar una columna la cual contiene el resultado de una operaciones aritméticas en n filas

In [62]:
# De esta forma calculo el Nuevo Total Facturado el cual debe ser igual a la columna Total Facturado

# Previamente se detecta gracias a la funcion .dtypes que las columnas "Precio", "Cantidad" y "Tot % bonif." son de tipo object, para este cálculo necesitamos que sean de tipo float.
# Procedemos a su conversion

if (varDataFrame['Precio'].dtypes == object):
    varDataFrame['Precio'] = varDataFrame['Precio'].str.replace('.', '').str.replace(',', '.').astype(float)

if (varDataFrame['Cantidad'].dtypes == object):
    varDataFrame['Cantidad'] = varDataFrame['Cantidad'].str.replace('.', '').str.replace(',', '.').astype(float)

if (varDataFrame['Tot % bonif.'].dtypes == object):
    varDataFrame['Tot % bonif.'] = varDataFrame['Tot % bonif.'].str.replace('.', '').str.replace(',', '.').astype(float)

if (varDataFrame['Total Facturado'].dtypes == object):
    varDataFrame['Total Facturado'] = varDataFrame['Total Facturado'].str.replace('.', '').str.replace(',', '.').astype(float)

varDataFrame.dtypes

varDataFrame['Nuevo Total'] = (varDataFrame['Precio'] * varDataFrame['Cantidad'])-(varDataFrame['Precio'] * varDataFrame['Cantidad'] * varDataFrame['Tot % bonif.'])

#varDataFrame['Nuevo Total']!='NaN'
#varDataFrame.info()

varDataFrame[['CAJA', 'SUCURSAL', 'Fecha de Venta', 'Precio', 'Cantidad', 'Tot % bonif.', 'Total Facturado', 'Vendedor', 'Nuevo Total' ]].head(100)

,CAJA,SUCURSAL,Fecha de Venta,Precio,Cantidad,Tot % bonif.,Total Facturado,Vendedor,Nuevo Total
0,Caja RMA,BIKE COMPANY S159,1/1/2024,NaN,NaN,NaN,NaN,Sin Vendedor,NaN
1,Caja RMA,BIKE COMPANY S159,2/1/2024,NaN,NaN,NaN,33900.0,Sin Vendedor,NaN
2,Caja RMA,BIKE COMPANY S159,3/1/2024,NaN,NaN,NaN,301400.0,Sin Vendedor,NaN
3,Caja RMA,BIKE COMPANY S159,4/1/2024,NaN,NaN,NaN,6900.0,Sin Vendedor,NaN
4,Caja RMA,BIKE COMPANY S159,5/1/2024,NaN,NaN,NaN,22800.0,Sin Vendedor,NaN
...,...,...,...,...,...,...,...,...,...
95,Caja RMA,PR SAN MARTIN 698,3/1/2024,NaN,NaN,NaN,62000.0,Sin Vendedor,NaN
96,Caja RMA,PR SAN MARTIN 698,4/1/2024,NaN,NaN,NaN,3800.0,Sin Vendedor,NaN
97,Caja RMA,PR SAN MARTIN 698,5/1/2024,NaN,NaN,NaN,73300.0,Sin Vendedor,NaN
98,Caja RMA,PR SAN MARTIN 698,6/1/2024,NaN,NaN,NaN,51300.0,Sin Vendedor,NaN
99,Caja RMA,PR SAN MARTIN 698,7/1/2024,NaN,NaN,NaN,NaN,Sin Vendedor,NaN